### ISSUE TITLE
ASAN reports memory leak

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#111]
Hi,

I have been enabling ASAN recently in Ravi - using gcc 9.3.1 on RHEL.

I see this error:

```
Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fefadb0a638 in __interceptor_malloc (/usr/lib64/libasan.so.5+0x10c638)
    #1 0x7fefad760426 in VARR_token_tcreate /home/dylan/github/ravi/mir/c2mir/c2mir.c:95
    #2 0x7fefad769e66 in define /home/dylan/github/ravi/mir/c2mir/c2mir.c:2045
    #3 0x7fefad76d346 in process_directive /home/dylan/github/ravi/mir/c2mir/c2mir.c:2784
    #4 0x7fefad76f7b0 in processing /home/dylan/github/ravi/mir/c2mir/c2mir.c:3267
    #5 0x7fefad770b49 in pre /home/dylan/github/ravi/mir/c2mir/c2mir.c:3468
    #6 0x7fefad7a6dad in c2mir_compile /home/dylan/github/ravi/mir/c2mir/c2mir.c:12342
    #7 0x7fefad7a7c23 in MIR_compile_C_module /home/dylan/github/ravi/src/ravi_mirjit.c:395

```
This is just the relevant MIR stack trace. I am not sure if I am doing something wrong

PS: I should add that I haven't updated my copy of MIR recently so the line numbers may be a bit off.

**Comment by dibyendumajumdar** [comment]
https://github.com/vnmakarov/mir/pull/112

**Comment by dibyendumajumdar** [comment]
Resolved
