### ISSUE TITLE
Assertion failure in MIR

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#27]
Hi,

I am hitting an assertion failure in MIR:

```
wrong destroy for uint8_travi: /home/dylan/github/mir/mir-varr.h:22: mir_var_assert_fail: Assertion `0' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffffe840801 in __GI_abort () at abort.c:79
#2  0x00007ffffe83039a in __assert_fail_base (fmt=0x7ffffe9b77d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x81527f7 "0", file=file@entry=0x8153188 "/home/dylan/github/mir/mir-varr.h",
    line=line@entry=22, function=function@entry=0x8154f80 <__PRETTY_FUNCTION__.2808> "mir_var_assert_fail")
    at assert.c:92
#3  0x00007ffffe830412 in __GI___assert_fail (assertion=0x81527f7 "0",
    file=0x8153188 "/home/dylan/github/mir/mir-varr.h", line=22,
    function=0x8154f80 <__PRETTY_FUNCTION__.2808> "mir_var_assert_fail") at assert.c:101
#4  0x00000000080a83a7 in mir_var_assert_fail ()
#5  0x00000000080ab27c in VARR_uint8_tdestroy ()
#6  0x00000000080c838d in machine_finish ()
#7  0x00000000080bd288 in code_finish ()
#8  0x00000000080afcf0 in MIR_finish ()
#9  0x0000000008087fe6 in raviV_close (L=0x858a280) at /home/dylan/github/ravi/src/ravi_mirjit.c:194
#10 0x0000000008042d64 in close_state (L=0x858a280) at /home/dylan/github/ravi/src/lstate.c:280
#11 0x000000000804360c in lua_close (L=0x858a280) at /home/dylan/github/ravi/src/lstate.c:426
#12 0x00000000080195b3 in main (argc=3, argv=0x7ffffffee098) at /home/dylan/github/ravi/src/lua.c:637
```

I will add any more information I can obtain.

**Comment by vnmakarov** [comment]
Thank you for reporting this, Dibyendu.  The assert raises when we destroy variable array repeatedly.

I looked at the code and it seems that the global state was not removed completely (there is still one global varr outside the context).  So if you are using more one context, it might happen.

I'll fix this on this week.

**Comment by dibyendumajumdar** [comment]
I think I am only using 1 context but I will check if somehow multiple are being created.

**Comment by vnmakarov** [comment]
I've removed the found global variable.  Here is the patch
https://github.com/vnmakarov/mir/commit/bbc8fc4b8a4163e906e5a1959eddb55174c526c3

**Comment by dibyendumajumdar** [comment]
@vnmakarov Thank you I will apply and retest and report back.

**Comment by dibyendumajumdar** [comment]
@vnmakarov Confirm this issue appears to be fixed by your patch.
